### ISSUE TITLE
Breaking changes since #6

### ISSUE THREAD

**Issue by vbabenkoru** [dockhippie/elasticsearch#14]
We've been using the 5.6 image in our `docker-compose`, but since the changes in #6, our config doesn't work anymore and requires full reconfiguration. Is there a way to keep backwards-compatible images available under a different tag or something like that?

**Comment by tboerger** [comment]
What do you mean by it needs to be reconfigured? The environment variables should be working as before. Mostly the internal structuring of the image has changed.

**Comment by vbabenkoru** [comment]
We've been providing a custom config file, and the new version is overwiting it instead.

**Comment by tboerger** [comment]
In that case you could provide the env variable `ELASTICSEARCH_SKIP_TEMPLATES=true`, but in that case you also got to provide the jvm.options file, this is witten or skipped at https://github.com/dockhippie/elasticsearch/blob/master/v5.6/overlay/etc/container.d/15-config.sh
